# This file is automatically generated from tlnx, don't manually edit it.
# If you want to customize, edit 
# ~/.config/bash/.bashrc_uniq (it will be sourced at the end of this file)
# or create a new file and make it sourced by .bashrc_uniq.

HISTCONTROL=ignoreboth


# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac




set -o vi
bind -x '"\C-l": clear'

# common shell settings
if [ -f "$HOME/.config/commonshell/common.sh" ]; then
    source "$HOME/.config/commonshell/common.sh"
fi

# unique user customizations
if [ -f "$HOME/.config/bash/.bashrc_uniq" ]; then
    source "$HOME/.config/bash/.bashrc_uniq"
fi 
# >>> TLNX shell block >>>
#     >>> TLNX clashctl patch >>>
clashctl_patch() {
local file1="/opt/clash/script/common.sh"
local file2="/opt/clash/script/clashctl.sh"
source "$file1" && source "$file2"
# Check mihomo service running
if ! systemctl is-active --quiet mihomo; then
	echo "[Mihomo Service] Mihomo is not running, you may manually run clashon."
else 
	MIXED_PORT=$($BIN_YQ '.mixed-port' "$CLASH_CONFIG_RUNTIME")
	if [ -z "$MIXED_PORT" ] || [ "$MIXED_PORT" == "null" ]; then
		echo "[Clashctl] Unable to determine mixed-port from $CLASH_CONFIG_RUNTIME"
	else
		unset http_proxy
		unset https_proxy
		unset HTTP_PROXY
		unset HTTPS_PROXY
		export http_proxy="http://127.0.0.1:$MIXED_PORT"
		export https_proxy="$http_proxy"
		export HTTP_PROXY="$http_proxy"
		export HTTPS_PROXY="$http_proxy"
	fi
fi
}

clashr() {
	sudo $BIN_YQ -i '.mode = "rule"' "$CLASH_CONFIG_RUNTIME"
	clashrestart
	_okcat "已切换到规则模式"
	clashctl tun
}

clashg() {
	sudo $BIN_YQ -i '.mode = "global"' "$CLASH_CONFIG_RUNTIME"
	clashrestart
	_okcat "已切换到全局模式"
	clashctl tun
}

clasht() {
	if clashctl tun 2>&1 | grep -q "关闭"; then
		clashctl tun on
	elif clashctl tun 2>&1 | grep -q "启用"; then
		clashctl tun off
	else
		clashctl tun
	fi
}

clashctl_patch
alias clash="clashctl proxy"
#     <<< TLNX clashctl patch <<<
# <<< TLNX shell block <<<
