#!/bin/bash

# Vim module - install and configure Vim

vim_install() {
	log "INFO" "Installing Vim..."
	sudo apt-get update 2>&1 | tee -a "$LOG_FILE"
	sudo apt-get install -y vim 2>&1 | tee -a "$LOG_FILE"
	
	if [ $? -eq 0 ]; then
		log "INFO" "Vim installed successfully"
	else
		log "ERROR" "Vim installation failed"
		return 1
	fi
}

vim_configure() {
	log "INFO" "Configuring Vim..."
	local vimrc="$HOME/.vimrc"
	
	if [ -f "$vimrc" ]; then
		log "INFO" ".vimrc already exists, skipping configuration"
		return 0
	fi

	cat > "$vimrc" <<EOF
" Generated by TLNX
set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on
set number
set cursorline
set shiftwidth=4
set tabstop=4
set expandtab
set nobackup
set scrolloff=10
set nowrap
set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set showmatch
set hlsearch
set history=1000
set wildmenu
set wildmode=list:longest
set wildignore=*.o,*~,*.pyc
set ruler
set laststatus=2
EOF
	log "INFO" "Created basic .vimrc"
}

_vim_install() {
	log "INFO" "=== Starting Vim module ==="
	vim_install
	vim_configure
	log "INFO" "=== Vim module completed ==="
}
