-- This file is automatically generated from tlnx, don't manually edit it.
-- If you want to customize, edit 
-- ~/.config/nvim/init_uniq.lua (it will be sourced at the end of this file)

-- ==========================================================================
-- 1. 核心键位映射 (Keymaps - 你的定制需求)
-- ==========================================================================

-- 设置 Leader 键为空格 (Space)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }

-- >>> 需求 1: 在插入模式下，按 jk 快速回到 Normal 模式 (替代 Esc) <<<
keymap("i", "jk", "<Esc>", { desc = "Exit insert mode with jk" })
-- (可选:有些人也喜欢同时把 kj 映射了，防止手误，你可以取消下面这行的注释)
-- keymap("i", "kj", "<Esc>", opts)


-- >>> 需求 2: 在 Normal 模式下，用 ; 代替 : (无需按 Shift) <<<
keymap("n", ";", ":", { desc = "Enter command mode" })

-- [推荐] 既然 ; 被占用了，建议把 : 映射回原本的 ; 功能
-- 原本 ; 的功能是：重复上一次 f, t, F, T 的行内查找
keymap("n", ":", ";", { desc = "Repeat last f/t search" })


-- ==========================================================================
-- 2. 通用基础设置 (Common Options)
-- ==========================================================================
local opt = vim.opt

-- 外观与行号
opt.number = true             -- 显示绝对行号
opt.relativenumber = true     -- 显示相对行号 (配合 jk 移动非常方便)
opt.cursorline = true         -- 高亮当前行
opt.termguicolors = true      -- 开启真彩色支持
opt.signcolumn = "yes"        -- 左侧预留符号列，防止代码抖动

-- 缩进 (Tab = 4 空格)
opt.tabstop = 4               -- 1 个 Tab 代表 4 个空格
opt.shiftwidth = 4            -- 缩进时的宽度
opt.expandtab = true          -- 将 Tab 自动转化为空格
opt.autoindent = true         -- 新行对齐上一行

-- 搜索行为
opt.ignorecase = true         -- 搜索时忽略大小写
opt.smartcase = true          -- 智能大小写 (输入大写时才严格匹配)
opt.hlsearch = true           -- 高亮搜索结果
opt.incsearch = true          -- 边输入边高亮

-- 系统剪贴板
-- 注意: 需要系统安装 xclip (Linux) 或 wl-clipboard (Wayland)
opt.clipboard:append("unnamedplus")

-- 窗口与滚动
opt.splitright = true         -- 竖分屏在新窗口右边
opt.splitbelow = true         -- 横分屏在新窗口下边
opt.scrolloff = 8             -- 光标上下保留 8 行视野

-- ==========================================================================
-- 3. 其他实用快捷键推荐 (Bonus Keymaps)
-- ==========================================================================

-- <Esc> 取消高亮搜索 (非常常用)
keymap("n", "<Esc>", "<cmd>nohlsearch<CR>", opts)

-- 快速保存 (Ctrl + s)
keymap({ "n", "i", "v" }, "<C-s>", "<cmd>w<CR><Esc>", { desc = "Save file" })

-- 窗口间跳转 (Ctrl + hjkl) 代替 Ctrl+w+h...
keymap("n", "<C-h>", "<C-w>h", opts)
keymap("n", "<C-j>", "<C-w>j", opts)
keymap("n", "<C-k>", "<C-w>k", opts)
keymap("n", "<C-l>", "<C-w>l", opts)

-- 调整缩进后保持选中状态 (Visual模式下)
keymap("v", "<", "<gv", opts)
keymap("v", ">", ">gv", opts)

-- ==========================================================================
-- 4. 插件管理器占位符 (Plugins)
-- ==========================================================================
-- 如果你以后想加插件 (例如 lazy.nvim)，代码通常写在这里
-- 目前这个文件是纯 Lua 配置，不需要下载任何东西即可运行。






-- ==========================================================================
-- 加载当前目录下的本地配置 (Project Local Config)
-- ==========================================================================
-- 获取当前路径下的 init_uniq.lua 绝对路径
local local_config = vim.fn.getcwd() .. "/init_uniq.lua"

-- 检测文件是否可读 (filereadable 返回 1 表示存在且可读)
if vim.fn.filereadable(local_config) == 1 then
    -- (可选) 打印一条消息提示已加载，方便调试，不需要可以注释掉
    -- vim.notify("Loading local config: " .. local_config)
    
    -- 使用 source 命令加载该文件
    vim.cmd("source " .. local_config)
end