# This file is automatically generated from tlnx, don't manually edit it.
# If you want to customize, edit 
# ~/.config/zsh/.zshrc_uniq (it will be sourced at the end of this file)
# or create a new file and make it sourced by .zshrc_uniq.


# For fixing some apps which injects stuff into $HOME/.zshrc
[ -f $HOME/.zshrc ] &&
source $HOME/.zshrc

# ZIM configuration
export ZIM_HOME="$ZDOTDIR/.zim"
export ZIM_CONFIG_FILE="$ZDOTDIR/.zimrc"
if [[ ! $ZDOTDIR/.zim/init.zsh -nt $ZDOTDIR/.zimrc ]]; then
  source $ZDOTDIR/.zim/zimfw.zsh init
fi
source ${ZIM_HOME}/init.zsh 


# common shell settings
if [ -f ~/.config/commonshell/common.sh ]; then
    source ~/.config/commonshell/common.sh
fi


# unique user customizations
if [ -f ~/.config/zsh/.zshrc_template ]; then
    source ~/.config/zsh/.zshrc_template
fi



# unique user customizations
if [ -f ~/.config/zsh/.zshrc_uniq ]; then
    source ~/.config/zsh/.zshrc_uniq
fi